= Professionelle Softwareentwicklung: Projekt 2

== Aufgabe 1: Personas

|===
|Name | Hintergrund | Ziel

a| Dennis

|

Dennis studiert im achten Semester Informationswissenschaft and der HHU. Er bearbeitet dieses Semester sowohl das "Programmierpraktikum" als auch das "DBS-Programmierpraktikum ".

Das erste Mal programmiert hat er in der Veranstaltung "Programmierung" im ersten Semester.
Er ist anderen Betriebssystemen gegenüber nicht abgeneigt, hat dennoch auf all seinen Geräten Win10 installiert.

An der aktuellen Situation der Abgabesysteme ärgert ihn nicht nur die langsame Geschwindigkeit, sondern vor allem, dass es keine Einheitliche Lösung, die Universitätsübergreifend genutzt wird gibt.
Er wünscht sich außerdem eine Funktion seine Kurse für sich selber grafisch anzuordnen oder farblich zu gestalten, da es ihm bereits passiert ist, dass er nach einer langen Nacht ohne viel Schlaf ein Projekt bei der Abgabe für "Programmierpraktikum" anstatt "DBS-Programmierpraktikum" abgegeben hat.

|
Dennis möchte die letzten Scheine, die er noch für seinen Bachelor benötigt möglichst reibungslos abschließen. Dazu zählt unter anderem das "Programmierpraktikum".
|===

|===
|Name | Hintergrund | Ziel

a| Daniel

|

Daniel studiert Informatik, er hat das  "Programmierpraktikum" bereits vor langem abgeschlossen, nun arbeitet er als Korrektor für das "Programmierpraktikum" um sich etwas
Geld neben seinem Studium dazu zu verdienen.

Daniel programmiert bereits seit Jahren und ist auch in seiner Freizeit in der Modding Community einiger Computerspiele unterwegs. Er zieht es vor unter Linux zu arbeiten,
da er aber auch gerne Computerspiele spielt hat er auf seinem Rechner zuhause ebenfalls Windows installiert.

Ihm ist wichtig, dass die Abgaben der Studenten unter allen Korrektoren gleichmäßig verteilt werden, wobei es ihn nicht sauer machen würde, wenn er weniger zu tun hat.
Am liebsten hätte er ein Tool, das direkt nach Abgabefrist die Projekte and die Korrektoren verteilt. Daniel wünscht sich außerdem, dass das Abgabesystem eine Funktion hätte,
mit der er bei Nachfragen zur Korrektur mit dem Studenten kommunizieren kann, ohne seine E-Mail zu benutzen. Am liebsten hätte er diese Funktion aber um immer direkt zu wissen
auf welche Abgabe sich der Schriftverkehr bezieht.
|
Daniel möchte sich während er dabei ist sein Studium abzuschließen etwas Geld dazu verdienen mit etwas das ihm Spaß macht. Außerdem freut er sich, wenn er anderen Studenten weiterhelfen kann.
|===



== Aufgabe 2: Abgabesystem

_Lösung für Aufgabe 2_

== Aufgabe 3: Namensfindung

_Lösung für Aufgabe 3_

== Aufgabe 4: Funktionsumfang

Ein Teil des neuen Abgabesystems könnte eine Funktion, wie in Aufgabenteil 1 bereits angedeutet, die es Korrekteren ermöglicht die  Abgabe zu kommentieren.
Der Student sollte außerdem die Möglichkeit haben nach seiner Korrektur über dieses System mit dem Korrektor zu kommunizieren falls Rückfragen vorhanden sind.
Dieses System würde den Schriftverkehr über die Universitäts-E-Mail überflüssig machen, was von Vorteil sein kann, da es schonmal vorkommt, dass das Postfach der
Uniadresse einige Tage nicht auf neue Nachrichten geprüft wird. In dem Zusammenhang wäre eine optionale Benachrichtigung über ein neues Kommentar zu einer Korrektur gut vorstellbar.
Sollte es bei einer Korrektur zu einem Streitfall kommen wäre es praktisch, wenn Professoren bzw. die Zuständigen für die Veranstaltung Zugriff auf das Geschriebene haben.

Eine weitere praktische Funktion, die das neue Abgabesystem haben könnte, wäre ein System, dass dem Verantwortlichen der Veranstaltung ermöglicht einzustellen ob und
wenn wie lange es eine Nachbearbeitungszeit gibt. Diese würde dann automatisch ablaufen sobald eine Korrektur eingereicht wurde. In diesen Kontext wäre auch eine Funktion,
die Joker wie in dieser Veranstaltung berücksichtig und dem Studenten die Möglichkeit gibt über das System den Joker direkt einzulösen. Länge und Anzahl
der Joker müssten natürlich im Vorfeld einstellbar sein. Dies würde ebenfalls den E-Mail-Verkehr reduzieren und vermutlich auch den Umgang mit solchen Regelungen erleichtern und
übersichtlicher machen. Es wäre auch gut, wenn der Admin der Veranstaltung die Möglichkeit hat die Abgabefrist für Studenten zu erhöhen, falls dieses Mal von Nöten sein sollte.









== Kommentare

_Falls Sie noch zusätzliche Anmerkungen für die Korrektur haben_
